import type { Metadata } from "next";
import { WebsitePlanForm } from "./website-plan-form";
import s from "./website-first.module.css";

const title = "A better website comes first | Booked Out";
const description = "A professional website for established local service businesses. Defined scope, a fixed project quote, 50% to start and 50% before launch. Private offer preview.";
export const metadata: Metadata = {
  title, description, robots: { index: false, follow: false },
  alternates: { canonical: "/website-first" },
  openGraph: { title, description, url: "/website-first", images: [] },
  twitter: { card: "summary", title, description, images: [] },
};
const included = [
  ["A site that feels like you", "Mobile-first design and clear copy for your services, service area and next step. Up to seven core pages, agreed before the build."],
  ["A clear path to contact", "Visible call links and one focused inquiry form, routed to your chosen inbox. We test delivery with you before launch."],
  ["Tracking from day one", "Analytics setup and agreed form-success and contact-click events, with a documented baseline. Clicks are not counted as booked jobs."],
  ["A considered handover", "Two consolidated revision rounds, responsive checks and a launch walkthrough. Hosting, access and ongoing costs are spelled out in your quote."],
];
const faq = [
  ["What does the website cost?", "You receive a fixed project quote after we confirm the pages, content and technical needs. No work starts until you approve the scope and price. The payment model is 50% deposit to reserve and start the build, then 50% before launch."],
  ["Am I signing up for a monthly plan?", "No. The website is a standalone project. Hosting and any third-party costs are identified in your quote. Ongoing care, CRM, follow-up, reviews, SEO and paid ads are separate, optional decisions after launch."],
  ["What will my website plan include?", "A recommended page outline, an initial design direction and the scope needed for a fixed quote. We start by confirming your business details by email. This is a planning conversation, not a completed custom design or an automatic booking."],
  ["When can we launch?", "We agree a schedule after reviewing scope, access, content and your approval availability. We do not promise a launch date before those are confirmed. Changes to scope or late approvals can change the schedule."],
  ["What do you need from me?", "Accurate service and business details, brand assets you have permission to use, domain access and one person to consolidate feedback. We help organize the website copy, but you approve all factual claims."],
  ["Who controls the website?", "Your domain and business accounts stay client controlled. The written quote defines platform, file handover, licenses and hosting arrangements before you pay. We review access and handover with you at launch."],
  ["Will this guarantee more leads?", "No. We build a clearer website and test the contact and tracking foundations. Traffic, competition, demand and your team's response all affect results. We do not guarantee leads, rankings, bookings or revenue."],
];
function Brand() { return <a className={s.brand} href="#main" aria-label="Booked Out, back to top">BOOKED<span>OUT</span><i aria-hidden="true" /></a>; }
function CTA() { return <a className={s.cta} href="#website-plan">Request My Website Plan <span aria-hidden="true">↗</span></a>; }
function Label({ children }: { children: React.ReactNode }) { return <p className={s.label}>{children}</p>; }
function Preview() {
  return <figure className={s.preview} aria-label="Illustrative home-service website concept, not a client result">
    <div className={s.browserBar}><span aria-hidden="true">● ● ●</span><span>Website direction / illustrative concept</span></div>
    <div className={s.mockSite}>
      <div className={s.mockNav}><strong>YOUR COMPANY<span>HOME SERVICES</span></strong><span>Local expertise. Clear next steps.</span></div>
      <div className={s.mockHero}><div><p>YOUR TRADE. YOUR NEIGHBORHOOD.</p><h2>Good work.<br />Close to home.</h2><p>Tell homeowners what you do,<br />where you work and how to reach you.</p><span className={s.mockButton}>Request a service visit ↗</span></div><div className={s.house} aria-hidden="true"><svg viewBox="0 0 220 240"><path d="M20 109 110 36l90 73v107H20Z" fill="#d3c7ad"/><path d="m8 113 102-84 102 84" fill="none" stroke="#282d29" strokeWidth="8"/><path d="M88 216v-74h46v74" fill="#545f4e"/><path d="M42 125h29v38H42zm108 0h29v38h-29z" fill="#f7f3e8"/><path d="M170 54v-30h18v45" fill="#282d29"/><path d="M0 218h220" stroke="#282d29" strokeWidth="3"/></svg></div></div>
      <div className={s.mockServices}><span>01 &nbsp; Your services</span><span>02 &nbsp; Your service area</span><span>03 &nbsp; Your contact path</span></div>
    </div>
    <figcaption><strong>Designed to make the next step clear.</strong><span>Sample layout only. Your direction starts with your business.</span></figcaption>
  </figure>;
}
export default function WebsiteFirstPage() {
  return <div className={s.page}>
    <a className={s.skip} href="#main">Skip to content</a>
    <div className={s.previewNotice}>PRIVATE PREVIEW <span>Website-first offer · proposed direction</span></div>
    <header className={s.header}><Brand /><nav aria-label="Page"><a href="#included">What’s included</a><a href="#process">How it works</a></nav><CTA /></header>
    <main id="main">
      <section className={`${s.wrap} ${s.hero}`}><div className={s.heroCopy}><Label>Booked Out / Websites for local service businesses</Label><h1>You do good work.<br />Your website<br /><em>should show it.</em></h1><p className={s.deck}>A professional website that makes your services clear and your business easy to contact. Start with the site. Add growth services when they make sense.</p><CTA /><p className={s.fine}>Fixed project quote. 50% to start. 50% before launch.<br />No required marketing retainer.</p></div><Preview /></section>
      <div className={`${s.wrap} ${s.foundationStrip}`}><span>THE FIRST DELIVERABLE</span><strong>A website built around your business.</strong><span>Clear scope <i /> Tested contact path <i /> Tracking foundations</span></div>
      <section className={`${s.light} ${s.section}`} id="included"><div className={s.wrap}><div className={s.sectionHeading}><div><Label>01 / The website project</Label><h2>More than a new look.<br />A useful foundation.</h2></div><p>Your website should explain the work you do, give visitors a reason to trust you and make contacting your team straightforward.</p></div><div className={s.includeGrid}>{included.map(([heading, copy], index) => <article key={heading}><span className={s.number}>0{index + 1}</span><h3>{heading}</h3><p>{copy}</p></article>)}</div><p className={s.scopeNote}>Recommended starting scope: one business, one location, one domain. Final page list, integrations, delivery schedule and price are confirmed in writing before payment.</p></div></section>
      <section className={`${s.section} ${s.process}`} id="process"><div className={s.wrap}><Label>02 / A clear way forward</Label><h2>Know what happens.<br />Know what you’re paying for.</h2><div className={s.steps}><article><span>01 / PLAN</span><h3>Agree the direction.</h3><p>We confirm your priorities, recommend the pages and show the direction. You approve a fixed project quote and scope before work begins.</p><strong>No payment to request your plan</strong></article><article><span>02 / BUILD</span><h3>Make it your own.</h3><p>A 50% deposit reserves and starts the build. We prepare the design and copy, connect the foundations and work through the agreed revisions.</p><strong>50% deposit to start</strong></article><article><span>03 / LAUNCH</span><h3>Put it to work.</h3><p>Review the finished site and launch checks. Pay the remaining balance before launch, then receive your walkthrough and documented handover.</p><strong>50% balance before launch</strong></article></div></div></section>
      <section className={`${s.section} ${s.why}`}><div className={`${s.wrap} ${s.whyGrid}`}><div><Label>03 / Why website first</Label><h2>Start with something<br />you can see.</h2></div><div><p className={s.large}>You do not need to buy an entire marketing program to get a better website.</p><p>First, build a place that explains your business and gives visitors a clear next step. Set up the tracking. Confirm where inquiries go.</p><p>Then use what you learn to decide what needs attention next. That might be maintenance, follow-up or more visibility. It does not have to be everything.</p><CTA /></div></div></section>
      <section className={`${s.section} ${s.light}`}><div className={s.wrap}><div className={s.sectionHeading}><div><Label>04 / After the website is live</Label><h2>Your next move.<br />Not a required bundle.</h2></div><p>Optional services are scoped and quoted separately after launch. Choose the support that fits the next problem, not a package you have to grow into.</p></div><div className={s.ladder}>{[["Keep it healthy", "Website care", "Maintenance, updates and agreed improvements to keep the site useful."],["Handle the handoff", "CRM, follow-up & reviews", "Organize inquiries, support timely replies and ask real customers for honest reviews."],["Build visibility", "SEO & paid ads", "Consider search work or advertising once the site and inquiry process are ready. Media spend is separate."]].map(([label, heading, copy], i) => <article key={label}><span>0{i + 1} / {label}</span><h3>{heading}</h3><p>{copy}</p></article>)}</div><p className={s.scopeNote}>No automated SMS is included in the website project. Any future messaging requires separate scope, consent and compliance review.</p></div></section>
      <section className={`${s.section} ${s.fit}`}><div className={`${s.wrap} ${s.fitGrid}`}><div><Label>05 / The fit check</Label><h2>For good operators.<br />Ready for a better site.</h2><p>Built for established, owner-operated local service businesses. Our initial focus is HVAC in the Austin area.</p></div><div><h3>A good starting point</h3><ul><li>You have real services and a reputation to represent accurately.</li><li>You can provide assets, access and timely feedback.</li><li>Your team can respond to the inquiries it receives.</li></ul></div><div><h3>Not the right project</h3><ul><li>You need guaranteed leads or immediate revenue.</li><li>You want unlimited revisions or a custom software platform.</li><li>You need someone to run every part of marketing from day one.</li></ul></div></div></section>
      <section className={`${s.section} ${s.faq}`}><div className={`${s.wrap} ${s.faqGrid}`}><div><Label>06 / Before you decide</Label><h2>A few practical<br />questions, answered.</h2></div><div>{faq.map(([q,a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>
      <section className={`${s.section} ${s.light}`} id="website-plan"><div className={`${s.wrap} ${s.request}`}><div><Label>YOUR WEBSITE STARTS HERE</Label><h2>Let’s give your work<br />a better home online.</h2><p className={s.deck}>Tell us where to start. We’ll confirm your business details by email, then discuss your page outline, design direction and project scope.</p><div className={s.planNote}><strong>Your next step is a plan, not a payment.</strong><p>No deposit, subscription or meeting is booked by this request. You decide after reviewing the scope and fixed quote.</p></div></div><div className={s.formCard}><Label>Request your website plan</Label><h3>A little about your business.</h3><WebsitePlanForm /></div></div></section>
    </main><footer className={`${s.wrap} ${s.footer}`}><Brand /><p>ICDC Ventures LLC, doing business as Booked Out.<br />A better website first. Room to grow after.</p><nav aria-label="Legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a></nav></footer>
  </div>;
}
