import type { Metadata } from "next";
import { WebsitePlanForm } from "./website-plan-form";
import s from "./website-first.module.css";

const title = "See your homepage direction before you hire us | Booked Out";
const description = "A tailored homepage concept for qualified HVAC and home-service businesses. See the direction, page map and fixed quote before committing to a build. Private offer preview.";
export const metadata: Metadata = {
  title, description, robots: { index: false, follow: false },
  alternates: { canonical: "/website-first" },
  openGraph: { title, description, url: "/website-first", images: [] },
  twitter: { card: "summary", title, description, images: [] },
};
const faq = [
  ["Is this a free website?", "No. There is no charge to request a concept. We confirm fit by email first. Accepted businesses receive a tailored homepage direction, recommended page map and fixed build quote. It is a design proposal, not a finished website or a promise of a concept for every submission. You can decline the build."],
  ["What will the full build cost?", "We quote a fixed price after confirming your pages, content and technical needs. Hosting and third-party costs are itemized. If you approve the direction and quote, a 50% deposit starts the full build. The remaining 50% is due before launch."],
  ["Do I have to buy ongoing marketing?", "No. You can stop with the website. Website care, CRM, follow-up, reviews, SEO and paid ads are optional and scoped separately. Hosting still needs a home and a budget; we document that arrangement before you pay."],
  ["Can you use my current domain?", "We review your current platform and domain access before quoting. Your domain and business accounts stay client controlled. Platform, file handover, licenses and hosting responsibilities are defined in writing before deposit."],
  ["What do you need, and when can we launch?", "We need accurate service details, authorized brand assets, access and one person to approve the work. We agree a schedule once those requirements and the scope are clear. There is no preset launch promise or unlimited revision allowance."],
  ["Will a new site guarantee more calls?", "No. Your website can make services easier to understand and contact easier to initiate. Demand, traffic quality, competition and your team’s response still affect results. We do not guarantee leads, rankings, bookings or revenue."],
];
function Brand() { return <a className={s.brand} href="#main" aria-label="Booked Out, back to top">BOOKED<span>OUT</span><i aria-hidden="true">↗</i></a>; }
function CTA() { return <a className={s.cta} href="#website-plan">Request My Homepage Concept <span aria-hidden="true">↗</span></a>; }
function Label({ children }: { children: React.ReactNode }) { return <p className={s.label}>{children}</p>; }
function Equipment({ id }: { id: string }) {
  return <svg viewBox="0 0 320 340" className={s.equipment} aria-hidden="true"><defs><linearGradient id={`${id}-cabinet`} x1="0" x2="1"><stop stopColor="#cbc5b6"/><stop offset=".5" stopColor="#eee9dd"/><stop offset="1" stopColor="#a19c90"/></linearGradient><pattern id={`${id}-vents`} width="7" height="7" patternUnits="userSpaceOnUse"><path d="M0 1h7" stroke="#68685d" strokeWidth="2"/></pattern></defs><ellipse cx="165" cy="300" rx="135" ry="18" fill="#000" opacity=".13"/><path d="m50 65 167-26 54 38-165 31Z" fill="#e5dfd1"/><path d="m217 39 54 38v205l-54-23Z" fill="#898b80"/><path d="M50 65 217 39v220L50 284Z" fill={`url(#${id}-cabinet)`}/><path d="m65 84 137-21v173L65 258Z" fill={`url(#${id}-vents)`}/><g transform="translate(134 157) rotate(-8)"><circle r="67" fill="#41493f" stroke="#abae9e" strokeWidth="4"/><g fill="#858e7e"><path d="M0 0C-71-26-63-68-15-57 4-52 17-22 0 0Z"/><path d="M0 0C57-48 89-19 57 19 43 34 11 32 0 0Z"/><path d="M0 0C17 74-23 88-40 41-48 21-28-5 0 0Z"/></g><g fill="none" stroke="#bbc0ad" strokeWidth="1.3"><circle r="59"/><circle r="48"/><circle r="36"/><circle r="23"/><path d="M-65 0H65M0-65V65M-46-46 46 46M-46 46 46-46"/></g><circle r="9" fill="#d9dacb"/></g><path d="m59 276 20-3v18l-20 4Zm133-21 17-3v18l-17 4Z" fill="#3c4339"/><path d="m230 97 27 18v138l-27-14Z" fill={`url(#${id}-vents)`}/><path d="m63 74 54-8" stroke="#faf9ee" strokeWidth="3"/></svg>;
}
function Preview() {
  return <figure className={s.presentation}>
    <div className={s.presentationTop}><span>ON THE DRAWING BOARD / 01</span><span>Illustrative HVAC concept · not a client project</span></div>
    <div className={s.conceptStage}>
      <div className={s.conceptNote}><span className={s.noteIndex}>A</span><strong>A reason to<br/>choose your crew.</strong><p>Your services, your area,<br/>your business’s character.</p></div>
      <div className={s.desktopMock} aria-label="Illustrative desktop homepage for fictional Fieldwork Heating and Air">
        <div className={s.browserBar}><span>● ● ●</span><span>Homepage / desktop direction</span><span>↗</span></div>
        <div className={s.mockNav}><b>FIELDWORK<span>HEATING & AIR</span></b><span>Our services &nbsp; Our people &nbsp; Service area</span><i>Request service ↗</i></div>
        <div className={s.mockHero}><div><span className={s.mockEyebrow}>AUSTIN AREA / HEATING & COOLING</span><p className={s.mockHeadline}>Texas heat.<br/>Meet your match.</p><p>AC repair, replacement and maintenance.<br/>Tell us what’s going on. We’ll take it from here.</p><span className={s.mockButton}>Let’s get your air back ↗</span></div><div className={s.productArt}><span>COMFORT.<br/>BACK IN<br/>YOUR CORNER.</span><Equipment id="desktop" /></div></div>
        <div className={s.mockBottom}><strong>Good neighbors.<br/>Serious about the work.</strong><span>AC repair <i>↗</i></span><span>New systems <i>↗</i></span><span>Maintenance <i>↗</i></span></div>
      </div>
      <div className={s.phoneMock} aria-label="Illustrative mobile contact path"><div className={s.phoneSpeaker}/><div className={s.phoneNav}>FIELDWORK <span>☰</span></div><span className={s.mockEyebrow}>HEATING & AIR / AUSTIN</span><p className={s.phoneHeadline}>Texas heat.<br/>Meet your match.</p><div className={s.phoneArt}><Equipment id="mobile" /></div><p>Tell us what’s going on.<br/>We’ll take it from here.</p><div className={s.phoneCall}>Call the team <span>↗</span></div></div>
      <div className={s.contactNote}><span className={s.noteIndex}>B</span><span>A direct path from<br/><strong>“Can you help?” to contact.</strong></span></div>
    </div>
    <figcaption><span>Sample art direction only. Your concept starts with your business.</span><span>Desktop thinking. Mobile decisions.</span></figcaption>
  </figure>;
}
export default function WebsiteFirstPage() {
  return <div className={s.page}>
    <a className={s.skip} href="#main">Skip to content</a>
    <div className={s.previewNotice}>PRIVATE PREVIEW <span>Proposed website-first offer</span></div>
    <header className={`${s.wrap} ${s.header}`}><Brand/><span className={s.headerNote}>Independent thinking.<br/>Built for local business.</span><nav aria-label="Page"><a href="#concept">The concept</a><a href="#included">The build</a><a href="#website-plan">Request My Homepage Concept <span aria-hidden="true">↗</span></a></nav></header>
    <main id="main">
      <section className={`${s.wrap} ${s.hero}`}><Label>BOOKED OUT / FOR HVAC & HOME-SERVICE OWNERS</Label><div className={s.heroGrid}><h1>See the website we’d build for <span className={s.keep}>your business.</span><em>Before you hire us.</em></h1><div className={s.heroAside}><p className={s.deck}>You know your trade.<br/>Get a proper look at ours.</p><p>We’ll show qualified local-service owners a tailored homepage direction, a recommended page map and a fixed quote before asking for a build deposit.</p><CTA/><p className={s.fine}>Start with a fit check by email. No payment.<br/>No obligation to commission the build.</p></div></div><Preview/></section>
      <section className={`${s.wrap} ${s.concept}`} id="concept"><div className={s.sectionRail}><span>01</span><Label>THE FIRST THING YOU GET</Label></div><div className={s.conceptGrid}><div className={s.conceptLead}><h2>A direction you can see.<br/><em>Before you decide.</em></h2><div className={s.briefNote}><Label>THE BRIEF COMES FIRST</Label><p>We confirm your services, service area and priorities before designing. The direction should reflect how your business works, not just wear your logo.</p></div></div><div><p className={s.intro}>A proposal should show you more than a list of services. Here’s what we put in front of accepted businesses.</p><ol className={s.deliverables}><li><span>01 / LOOK & MESSAGE</span><div><h3>Your homepage direction</h3><p>A tailored visual concept showing how we’d introduce your business, present the work and lead a homeowner toward contact.</p></div></li><li><span>02 / THE REST OF THE SITE</span><div><h3>A recommended page map</h3><p>Which services deserve their own pages, where your service area belongs and what a homeowner needs before calling.</p></div></li><li><span>03 / THE BUILD DECISION</span><div><h3>A fixed scope and price</h3><p>The pages, revisions, technical needs and costs in writing. You can judge the direction and the investment together.</p></div></li></ol><p className={s.fine}>We confirm business fit and project needs first. This is a homepage design proposal, not a finished free website or an automatic acceptance.</p></div></div></section>
      <section className={s.demand}><div className={s.wrap}><div className={s.sectionRail}><span>02</span><Label>WHY THE WEBSITE COMES FIRST</Label></div><div className={s.demandGrid}><div><h2>The referral gets your name.<br/><em>The website gets the <span className={s.keep}>next look.</span></em></h2><p>A neighbor recommends your crew. A homeowner searches Google. Someone taps an ad while the house gets warmer. Different starting points, often the same destination.</p><p>When they compare tabs, your site needs to answer: do you handle this problem, do you work here, and how do I reach you?</p></div><div className={s.pathStory}><div className={s.sources}><span>A referral</span><span>A Google search</span><span>A paid click</span></div><div className={s.destination}><span>THE PLACE THEY CHECK</span><strong>Your website</strong><p>Services they recognize.<br/>An area they’re in.<br/>A team they can contact.</p><div className={s.pathActions}><span>Tap to call ↗</span><span>Send an inquiry ↗</span></div></div><p className={s.pathCaption}>Measure contact actions. Confirm delivery.<br/>Your team handles the conversation.</p></div></div><p className={s.demandClose}>Before paying to send more people there,<br/><strong>give them a destination worth choosing.</strong></p></div></section>
      <section className={`${s.wrap} ${s.build}`} id="included"><div className={s.sectionRail}><span>03</span><Label>IF YOU APPROVE THE DIRECTION</Label></div><div className={s.buildGrid}><div><h2>From first look<br/>to <em>the first inquiry.</em></h2><p>The full website project connects the pages a homeowner reads with the call or inquiry your team needs to receive.</p><div className={s.pageMap}><span>AN EXAMPLE PAGE MAP / UP TO 7 AGREED PAGES</span><strong>Home</strong><div><span>Services</span><span>AC repair</span><span>Installation</span><span>About</span><span>Service area</span><span>Contact</span></div></div></div><div className={s.buildSpecs}>{[
        ["Copy and design for the actual business", "Mobile-first copy and layouts for up to seven agreed pages. Real service details, approved claims and your brand assets. Two consolidated revision rounds."],
        ["A contact path that gets tested", "Visible call links and one focused inquiry form routed to your chosen inbox. We test delivery with you and confirm who owns the reply."],
        ["Tracking with honest definitions", "Analytics plus agreed contact-click and form-success events. A click is an action, not a booked job. You get a documented starting baseline."],
        ["The details behind the launch", "Page titles, descriptions, semantic structure, domain configuration and responsive QA. A launch walkthrough and documented access handover."]
      ].map(([heading,copy],i)=><article key={heading}><span>0{i+1}</span><div><h3>{heading}</h3><p>{copy}</p></div></article>)}</div></div><p className={s.scopeNote}>Starting scope: one business, one location, one domain. The final page list, platform, hosting, licenses, handover and schedule are agreed before deposit. Full SEO campaigns and custom software are not included.</p></section>
      <section className={s.process} id="process"><div className={s.wrap}><div className={s.processHeader}><div><Label>04 / THE MONEY & THE MILESTONES</Label><h2>See it first.<br/>Then decide.</h2></div><p>No retainer hidden inside a website project. You approve the direction and fixed quote before the full build begins.</p></div><div className={s.milestones}><article><span className={s.milestoneValue}>First look<span>NO DEPOSIT</span></span><h3>Confirm fit. Review the concept.</h3><p>We confirm your business by email. If the project fits, we prepare the homepage direction, page map and fixed quote for your decision.</p></article><article><span className={s.milestoneValue}>50%<span>TO START THE BUILD</span></span><h3>Approve the scope. Begin the work.</h3><p>Your deposit starts the agreed full build. We develop the pages, connect contact and tracking, and work through your revisions.</p></article><article><span className={s.milestoneValue}>50%<span>BEFORE LAUNCH</span></span><h3>Review the site. Make it live.</h3><p>Approve the finished site and launch checks. Pay the balance before launch, then receive your walkthrough and handover.</p></article></div></div></section>
      <section className={`${s.wrap} ${s.after}`}><div><Label>05 / AFTER LAUNCH, IF YOU NEED IT</Label><h2>A website can be<br/>the whole project.</h2><p>Or the starting point for the next problem you want to solve. Each expansion has its own scope and quote.</p></div><div className={s.expansions}><article><h3>Keep the site current</h3><p>Website care for updates, maintenance and agreed improvements.</p><span>OPTIONAL / WEBSITE CARE</span></article><article><h3>Follow through on inquiries</h3><p>CRM, email follow-up and honest customer review requests. No automated SMS is included.</p><span>OPTIONAL / CUSTOMER FOLLOW-UP</span></article><article><h3>Bring more people to it</h3><p>SEO or paid ads once the site and inquiry handling are ready. Media spend is separate.</p><span>OPTIONAL / SEARCH & ADVERTISING</span></article></div></section>
      <section className={s.questions}><div className={s.wrap}><div className={s.fit}><div><Label>06 / THE RIGHT WORKING RELATIONSHIP</Label><h2>For owners with<br/>real work to show.</h2></div><div><p>Our starting focus is established, owner-operated HVAC and home-service businesses around Austin. You have real work to show, can approve accurate content and have someone ready to answer inquiries.</p><p>If you need guaranteed leads, unlimited revisions or a custom software platform, this is not that project.</p></div></div><div className={s.faq}><h3>Before you<br/>make the request.</h3><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></div></section>
      <section className={`${s.wrap} ${s.request}`} id="website-plan"><div><Label>YOUR BUSINESS / OUR FIRST DIRECTION</Label><h2>Put your business<br/><em>on the <span className={s.keep}>drawing board.</span></em></h2><p className={s.deck}>Tell us which business is yours. We’ll confirm your services, area and project fit by email before preparing a concept.</p><div className={s.requestNote}><span aria-hidden="true">↗</span><p>You’re requesting a homepage direction.<br/><strong>You’re not hiring us yet.</strong></p></div><p className={s.fine}>No meeting is booked by this form. No deposit is taken.<br/>We review requests for fit; not every request is accepted.</p></div><div className={s.formCard}><Label>REQUEST / HOMEPAGE CONCEPT</Label><h3>Which business is yours?</h3><WebsitePlanForm/></div></section>
    </main><footer className={`${s.wrap} ${s.footer}`}><Brand/><p>ICDC Ventures LLC, doing business as Booked Out.<br/>Websites for businesses that do the work.</p><nav aria-label="Legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a></nav></footer>
  </div>;
}
